// Document numbering: prefix + 4-digit running number, generated by the store on save.
export const PREFIXES = {
  CUS: 'CUS', SUP: 'SUP', ITM: 'ITM',
  CR: 'CR', PR: 'PR', VQ: 'VQ', QC: 'QC', CQ: 'CQ', SO: 'SO',
  PO: 'PO', GRN: 'GRN', INW: 'INW', OUT: 'OUT', SI: 'SI', PI: 'PI',
}

export const emptyCounters = () =>
  Object.keys(PREFIXES).reduce((a, k) => ((a[k] = 0), a), {})

const pad = (n, w) => String(n).padStart(w, '0')

/** Mutates the counters object and returns the next document number. */
export function nextNo(counters, type) {
  const width = type === 'CUS' || type === 'SUP' ? 3 : 4
  counters[type] = (counters[type] || 0) + 1
  return `${PREFIXES[type]}-${pad(counters[type], width)}`
}

export const uid = (() => {
  let n = 0
  return (p = 'id') => `${p}_${Date.now().toString(36)}_${(n++).toString(36)}`
})()
