import { color, radius, font } from './tokens.js'

/**
 * Ant Design is the underlying primitive library; this maps our tokens onto it
 * so every antd component inherits the Toolsphoppe identity instead of the
 * default look.
 */
export const antdTheme = {
  token: {
    colorPrimary: color.primary,
    colorInfo: color.info,
    colorSuccess: color.success,
    colorWarning: color.warning,
    colorError: color.danger,
    colorText: color.text,
    colorTextSecondary: color.textSecondary,
    colorTextTertiary: color.textMuted,
    colorBorder: color.border,
    colorBorderSecondary: color.border,
    colorBgLayout: color.pageBg,
    colorBgContainer: color.card,
    borderRadius: radius.button,
    borderRadiusLG: radius.card,
    borderRadiusSM: radius.badge,
    fontFamily: font.family,
    fontSize: font.body,
    controlHeight: 38,
    controlHeightSM: 32,
    lineWidth: 1,
    wireframe: false,
  },
  components: {
    Layout: {
      siderBg: color.sidebar,
      headerBg: color.card,
      bodyBg: color.pageBg,
      headerHeight: 60,
      headerPadding: '0 24px',
    },
    Table: {
      headerBg: color.surfaceAlt,
      headerColor: '#475569',
      headerSplitColor: color.border,
      borderColor: color.border,
      rowHoverBg: '#F8FAFF',
      cellPaddingBlock: 14,
      cellPaddingInline: 14,
      cellPaddingBlockSM: 10,
      cellPaddingInlineSM: 12,
      cellFontSize: font.table,
      cellFontSizeSM: font.table,
      footerBg: color.surfaceAlt,
    },
    Button: {
      controlHeight: 38,
      controlHeightSM: 32,
      borderRadius: radius.button,
      fontWeight: 500,
      primaryShadow: 'none',
      defaultShadow: 'none',
      dangerShadow: 'none',
    },
    Input: { borderRadius: radius.input, activeShadow: `0 0 0 3px ${color.primaryLight}` },
    InputNumber: { borderRadius: radius.input, activeShadow: `0 0 0 3px ${color.primaryLight}` },
    Select: { borderRadius: radius.input, optionSelectedBg: color.primaryLight },
    DatePicker: { borderRadius: radius.input },
    Modal: { borderRadiusLG: radius.card, titleFontSize: 16, headerBg: color.card },
    Drawer: { footerPaddingBlock: 14, footerPaddingInline: 24 },
    Tabs: { itemSelectedColor: color.primary, inkBarColor: color.primary, horizontalItemGutter: 24 },
    Tag: { borderRadiusSM: radius.badge, defaultBg: '#F1F5F9', defaultColor: '#475569' },
    Menu: {
      darkItemBg: 'transparent',
      darkSubMenuItemBg: 'transparent',
      darkItemSelectedBg: color.sidebarActive,
      darkItemHoverBg: color.sidebarSecondary,
      darkItemColor: '#94A3B8',
      darkItemHoverColor: '#FFFFFF',
      darkItemSelectedColor: '#FFFFFF',
      itemHeight: 38,
      itemMarginInline: 8,
      itemBorderRadius: radius.button,
      iconMarginInlineEnd: 10,
    },
    Steps: { dotSize: 8 },
    Progress: { defaultColor: color.primary },
    Alert: { borderRadiusLG: radius.input },
    Message: { contentPadding: '10px 16px' },
  },
}
